### ISSUE TITLE
Automatic detection of Lutron Caseta SmartBridges

### ISSUE THREAD

**Issue by rhwood** [rnilssoncx/homebridge-pico#41]
I recently had my network drop all DHCP leases and change the IP addresses of connected devices after an extended power outage; the only thing that did not automagically recover was this plugin in Homebridge.

Lutron SmartBridges appear to always broadcast a mDNS/zeroconf/Bonjour service of `_lutron._tcp`, although this service does not appear to change if telnet is/is not enabled, it could be used to recognize a known SmartBridge when its IP address changes to allow the Homebridge to remain connected to the SmartBridge.

**Comment by rnilssoncx** [comment]
This could be done, but right now I try to focus my time improving the plugin on the usability side.  It can also support multiple bridges, so that would have to be sorted - most plugins shortcut on this.

Your issue is easy corrected by setting a fixed IP address through the Lutron app.

I'll put this on the backlog.  Maybe someone will do a pull request for this at some point.  Thanks for the request!
